/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qaops.automation.api.test;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import org.apache.http.HttpStatus;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import qaops.automation.api.domain.User;

import static io.restassured.RestAssured.basePath;
import static io.restassured.RestAssured.baseURI;
import static io.restassured.RestAssured.given;
import static io.restassured.RestAssured.when;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.notNullValue;

public class UserAlternativeTest {

    private static final String BASE_URL = "https://reqres.in";
    private static final String BASE_PATH = "/api";

    private String uri;

    @BeforeClass
    public static void setupAlternative() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
    }

    @Test
    public void testListUserMetadata() {
        String apiUri = getUri("/users");

        when().
            get(apiUri + "?page=2").
        then().
            statusCode(HttpStatus.SC_OK).
            body("page", is(2)).
            body("data", is(notNullValue()));
    }

    @Test
    public void testSuccessfullyCreateaUser() {
        User user = new User("rafael", "eng test");
        String apiUri = getUri("/users");

        given().
            contentType(ContentType.JSON).
            body(user).
        when().
            post(apiUri).
        then().
            statusCode(HttpStatus.SC_CREATED).
            body("name", is("rafael"));
    }

    private String getUri(String endpoint) {
        return BASE_URL + BASE_PATH + endpoint;
    }
}
